const colors = {
  white: '#ffffff',
  black: '#000000',
  grey0: '#d5d5d5',
  grey1: '#a6a6a6',
  red: '#e84118',
  blue: '#3679fe',
};

export const theme = {
  background: colors.white,
  text: colors.black,
  imageBackground: colors.grey0,
  label: colors.grey1,
  inputPlaceholder: colors.grey1,
  inputBorder: colors.grey1,
  errorText: colors.red,
  buttonBackground: colors.blue,
  buttonTitle: colors.white,
  buttonUnfilledTitle: colors.blue,
  headerTintColor: colors.black,
  imageButtonBackground: colors.grey1,
  imageButtonIcon: colors.white,
  spinnerBackground: colors.black,
  spinnerIndicator: colors.white,
  tabActiveColor: colors.blue,
  tabInactiveColor: colors.grey1,
  buttonLogout: colors.red,
  inputDisabledBackground: colors.grey0,
  listBorder: colors.grey0,
  listTime: colors.grey1,
  listDescription: colors.grey1,
  listIcon: colors.black,
  sendButtonActive: colors.blue,
  sendButtonInactive: colors.grey1,
};
